# Generated by Django 5.1.6 on 2025-02-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chapters', models.ManyToManyField(related_name='theorems', to='things.chapter')),
                ('class_levels', models.ManyToManyField(related_name='theorems', to='things.classlevel')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theorems', to='things.subject')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='theorem',
            field=models.ManyToManyField(related_name='lessons', to='things.theorem'),
        ),
    ]
