# Generated by Django 5.1.5 on 2025-02-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='solution',
        ),
    ]
