# Generated by Django 5.1.6 on 2025-02-08 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_chapter_class_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.subject'),
        ),
    ]
